//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BZFlag.Data.Flags {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlagStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlagStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BZFlag.Data.Flags.FlagStrings", typeof(FlagStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank is quick and nimble making it easier to dodge..
        /// </summary>
        internal static string AgilityDescription {
            get {
                return ResourceManager.GetString("AgilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string AgilityName {
            get {
                return ResourceManager.GetString("AgilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t see out window.  Radar still works..
        /// </summary>
        internal static string BlindnessDescription {
            get {
                return ResourceManager.GetString("BlindnessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blindness.
        /// </summary>
        internal static string BlindnessName {
            get {
                return ResourceManager.GetString("BlindnessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string BlueTeamDescription {
            get {
                return ResourceManager.GetString("BlueTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Team.
        /// </summary>
        internal static string BlueTeamName {
            get {
                return ResourceManager.GetString("BlueTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank can&apos;t stop bouncing..
        /// </summary>
        internal static string BouncyDescription {
            get {
                return ResourceManager.GetString("BouncyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouncy.
        /// </summary>
        internal static string BouncyName {
            get {
                return ResourceManager.GetString("BouncyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank burrows underground, impervious to normal shots, but can be steamrolled by anyone!.
        /// </summary>
        internal static string BurrowDescription {
            get {
                return ResourceManager.GetString("BurrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burrow.
        /// </summary>
        internal static string BurrowName {
            get {
                return ResourceManager.GetString("BurrowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t tell team colors.  Don&apos;t shoot teammates!.
        /// </summary>
        internal static string CBDescription {
            get {
                return ResourceManager.GetString("CBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorblindness.
        /// </summary>
        internal static string CBName {
            get {
                return ResourceManager.GetString("CBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes your tank invisible out-the-window.  Still visible on radar..
        /// </summary>
        internal static string CloakingDescription {
            get {
                return ResourceManager.GetString("CloakingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloaking.
        /// </summary>
        internal static string CloakingName {
            get {
                return ResourceManager.GetString("CloakingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t drive in reverse..
        /// </summary>
        internal static string FODescription {
            get {
                return ResourceManager.GetString("FODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Only.
        /// </summary>
        internal static string FOName {
            get {
                return ResourceManager.GetString("FOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing one tank kills that tank&apos;s whole team..
        /// </summary>
        internal static string GenoDescription {
            get {
                return ResourceManager.GetString("GenoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genocide.
        /// </summary>
        internal static string GenoName {
            get {
                return ResourceManager.GetString("GenoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots track a target.  Lock on with right button.  Can lock on or retarget after firing..
        /// </summary>
        internal static string GMDescription {
            get {
                return ResourceManager.GetString("GMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guided Missile.
        /// </summary>
        internal static string GMName {
            get {
                return ResourceManager.GetString("GMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string GreenTeamDescription {
            get {
                return ResourceManager.GetString("GreenTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Team.
        /// </summary>
        internal static string GreenTeamName {
            get {
                return ResourceManager.GetString("GreenTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank moves faster.  Outrun bad guys..
        /// </summary>
        internal static string HighSpeedDescription {
            get {
                return ResourceManager.GetString("HighSpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Speed.
        /// </summary>
        internal static string HighSpeedName {
            get {
                return ResourceManager.GetString("HighSpeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shots don&apos;t appear on other radars.  Can still see them out window..
        /// </summary>
        internal static string IBDescription {
            get {
                return ResourceManager.GetString("IBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible Bullet.
        /// </summary>
        internal static string IBName {
            get {
                return ResourceManager.GetString("IBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies type of nearest flag..
        /// </summary>
        internal static string IdentifyDescription {
            get {
                return ResourceManager.GetString("IdentifyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify.
        /// </summary>
        internal static string IdentifyName {
            get {
                return ResourceManager.GetString("IdentifyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar doesn&apos;t work.  Can still see..
        /// </summary>
        internal static string JammingDescription {
            get {
                return ResourceManager.GetString("JammingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamming.
        /// </summary>
        internal static string JammingName {
            get {
                return ResourceManager.GetString("JammingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank can jump.  Use Tab key.  Can&apos;t steer in the air..
        /// </summary>
        internal static string JumpingDescription {
            get {
                return ResourceManager.GetString("JumpingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumping.
        /// </summary>
        internal static string JumpingName {
            get {
                return ResourceManager.GetString("JumpingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoots a laser.  Infinite speed and range but long reload time..
        /// </summary>
        internal static string LaserDescription {
            get {
                return ResourceManager.GetString("LaserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser.
        /// </summary>
        internal static string LaserName {
            get {
                return ResourceManager.GetString("LaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t turn right..
        /// </summary>
        internal static string LTDescription {
            get {
                return ResourceManager.GetString("LTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Turn Only.
        /// </summary>
        internal static string LTName {
            get {
                return ResourceManager.GetString("LTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very fast reload but very short range..
        /// </summary>
        internal static string MachineGunDescription {
            get {
                return ResourceManager.GetString("MachineGunDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Gun.
        /// </summary>
        internal static string MachineGunName {
            get {
                return ResourceManager.GetString("MachineGunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In opponent&apos;s hud, you appear as a teammate..
        /// </summary>
        internal static string MasqueradeDescription {
            get {
                return ResourceManager.GetString("MasqueradeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masquerade.
        /// </summary>
        internal static string MasqueradeName {
            get {
                return ResourceManager.GetString("MasqueradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank has inertia.  Acceleration is limited..
        /// </summary>
        internal static string MomentumDescription {
            get {
                return ResourceManager.GetString("MomentumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentum.
        /// </summary>
        internal static string MomentumName {
            get {
                return ResourceManager.GetString("MomentumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank is super thin.  Very hard to hit from front but is normal size from side.  Can get through small openings..
        /// </summary>
        internal static string NarrowDescription {
            get {
                return ResourceManager.GetString("NarrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        internal static string NarrowName {
            get {
                return ResourceManager.GetString("NarrowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank can&apos;t jump..
        /// </summary>
        internal static string NoJumpDescription {
            get {
                return ResourceManager.GetString("NoJumpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Jumping.
        /// </summary>
        internal static string NoJumpName {
            get {
                return ResourceManager.GetString("NoJumpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NullFlagDescription {
            get {
                return ResourceManager.GetString("NullFlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NullFlagName {
            get {
                return ResourceManager.GetString("NullFlagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank becomes very large.  Can&apos;t fit through teleporters..
        /// </summary>
        internal static string ObesityDescription {
            get {
                return ResourceManager.GetString("ObesityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity.
        /// </summary>
        internal static string ObesityName {
            get {
                return ResourceManager.GetString("ObesityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can drive through buildings.  Can&apos;t backup or shoot while inside..
        /// </summary>
        internal static string OODescription {
            get {
                return ResourceManager.GetString("OODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscillation Overthruster.
        /// </summary>
        internal static string OOName {
            get {
                return ResourceManager.GetString("OOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string PurpleTeamDescription {
            get {
                return ResourceManager.GetString("PurpleTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Team.
        /// </summary>
        internal static string PurpleTeamName {
            get {
                return ResourceManager.GetString("PurpleTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting toggles Zoned effect.  Zoned tank can drive through buildings.  Zoned tank shoots Zoned bullets and can&apos;t be shot (except by superbullet, shock wave, and other Zoned tanks)..
        /// </summary>
        internal static string PZDescription {
            get {
                return ResourceManager.GetString("PZDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantom Zone.
        /// </summary>
        internal static string PZName {
            get {
                return ResourceManager.GetString("PZName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank turns faster.  Good for dodging..
        /// </summary>
        internal static string QuickTurnDescription {
            get {
                return ResourceManager.GetString("QuickTurnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Turn.
        /// </summary>
        internal static string QuickTurnName {
            get {
                return ResourceManager.GetString("QuickTurnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoots more often.  Shells go faster but not as far..
        /// </summary>
        internal static string RapidFireDescription {
            get {
                return ResourceManager.GetString("RapidFireDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Fire.
        /// </summary>
        internal static string RapidFireName {
            get {
                return ResourceManager.GetString("RapidFireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank driving controls are reversed..
        /// </summary>
        internal static string RCDescription {
            get {
                return ResourceManager.GetString("RCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Controls.
        /// </summary>
        internal static string RCName {
            get {
                return ResourceManager.GetString("RCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string RedTeamDescription {
            get {
                return ResourceManager.GetString("RedTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Team.
        /// </summary>
        internal static string RedTeamName {
            get {
                return ResourceManager.GetString("RedTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots bounce off walls.  Don&apos;t shoot yourself!.
        /// </summary>
        internal static string RiccoDescription {
            get {
                return ResourceManager.GetString("RiccoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riccochet.
        /// </summary>
        internal static string RiccoName {
            get {
                return ResourceManager.GetString("RiccoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t drive forward..
        /// </summary>
        internal static string RODescription {
            get {
                return ResourceManager.GetString("RODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReverseOnly.
        /// </summary>
        internal static string ROName {
            get {
                return ResourceManager.GetString("ROName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t turn left..
        /// </summary>
        internal static string RTDescription {
            get {
                return ResourceManager.GetString("RTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Turn Only.
        /// </summary>
        internal static string RTName {
            get {
                return ResourceManager.GetString("RTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoots through buildings.  Can kill Phantom Zone..
        /// </summary>
        internal static string SBDescription {
            get {
                return ResourceManager.GetString("SBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Bullet.
        /// </summary>
        internal static string SBName {
            get {
                return ResourceManager.GetString("SBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See stealthed, cloaked and masquerading tanks as normal..
        /// </summary>
        internal static string SeerDescription {
            get {
                return ResourceManager.GetString("SeerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seer.
        /// </summary>
        internal static string SeerName {
            get {
                return ResourceManager.GetString("SeerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting hit only drops flag.  Flag flies an extra-long time..
        /// </summary>
        internal static string ShieldDescription {
            get {
                return ResourceManager.GetString("ShieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string ShieldName {
            get {
                return ResourceManager.GetString("ShieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing destroys all tanks nearby.  Don&apos;t kill teammates!  Can kill tanks on/in buildings..
        /// </summary>
        internal static string ShockwaveDescription {
            get {
                return ResourceManager.GetString("ShockwaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock Wave.
        /// </summary>
        internal static string ShockWaveName {
            get {
                return ResourceManager.GetString("ShockWaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank is invisible on radar.  Shots are still visible.  Sneak up behind enemies!.
        /// </summary>
        internal static string StealthDescription {
            get {
                return ResourceManager.GetString("StealthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth.
        /// </summary>
        internal static string StealthName {
            get {
                return ResourceManager.GetString("StealthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroys tanks you touch but you have to get really close..
        /// </summary>
        internal static string SteamrollerDescription {
            get {
                return ResourceManager.GetString("SteamrollerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steamroller.
        /// </summary>
        internal static string SteamrollerName {
            get {
                return ResourceManager.GetString("SteamrollerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal flags.  Small and fast but can&apos;t kill..
        /// </summary>
        internal static string ThiefDescription {
            get {
                return ResourceManager.GetString("ThiefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        internal static string ThiefName {
            get {
                return ResourceManager.GetString("ThiefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank is small and can get through small openings.  Very hard to hit..
        /// </summary>
        internal static string TinyDescription {
            get {
                return ResourceManager.GetString("TinyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        internal static string TinyName {
            get {
                return ResourceManager.GetString("TinyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank can&apos;t stop firing..
        /// </summary>
        internal static string TRDescription {
            get {
                return ResourceManager.GetString("TRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Happy.
        /// </summary>
        internal static string TRName {
            get {
                return ResourceManager.GetString("TRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found the useless flag. Use it wisely..
        /// </summary>
        internal static string UselessDescription {
            get {
                return ResourceManager.GetString("UselessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useless.
        /// </summary>
        internal static string UselessName {
            get {
                return ResourceManager.GetString("UselessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish-eye lens distorts view..
        /// </summary>
        internal static string WADescription {
            get {
                return ResourceManager.GetString("WADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide Angle.
        /// </summary>
        internal static string WAName {
            get {
                return ResourceManager.GetString("WAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank can drive in air..
        /// </summary>
        internal static string WingsDescription {
            get {
                return ResourceManager.GetString("WingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings.
        /// </summary>
        internal static string WingsName {
            get {
                return ResourceManager.GetString("WingsName", resourceCulture);
            }
        }
    }
}
