//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BZFlag.Data.Flags {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlagStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlagStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BZFlag.Data.Flags.FlagStrings", typeof(FlagStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string BlueTeamDescription {
            get {
                return ResourceManager.GetString("BlueTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Team.
        /// </summary>
        internal static string BlueTeamName {
            get {
                return ResourceManager.GetString("BlueTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genocide.
        /// </summary>
        internal static string GenoName {
            get {
                return ResourceManager.GetString("GenoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guided Missile.
        /// </summary>
        internal static string GMName {
            get {
                return ResourceManager.GetString("GMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string GreenTeamDescription {
            get {
                return ResourceManager.GetString("GreenTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Team.
        /// </summary>
        internal static string GreenTeamName {
            get {
                return ResourceManager.GetString("GreenTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank moves faster.  Outrun bad guys..
        /// </summary>
        internal static string HighSpeedDescription {
            get {
                return ResourceManager.GetString("HighSpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Speed.
        /// </summary>
        internal static string HighSpeedName {
            get {
                return ResourceManager.GetString("HighSpeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible Bullet.
        /// </summary>
        internal static string IBName {
            get {
                return ResourceManager.GetString("IBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser.
        /// </summary>
        internal static string LaserName {
            get {
                return ResourceManager.GetString("LaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Gun.
        /// </summary>
        internal static string MachineGunName {
            get {
                return ResourceManager.GetString("MachineGunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        internal static string NarrowName {
            get {
                return ResourceManager.GetString("NarrowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NullFlagDescription {
            get {
                return ResourceManager.GetString("NullFlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NullFlagName {
            get {
                return ResourceManager.GetString("NullFlagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can drive through buildings.  Can&apos;t backup or shoot while inside..
        /// </summary>
        internal static string OODescription {
            get {
                return ResourceManager.GetString("OODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscillation Overthruster.
        /// </summary>
        internal static string OOName {
            get {
                return ResourceManager.GetString("OOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string PurpleTeamDescription {
            get {
                return ResourceManager.GetString("PurpleTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Team.
        /// </summary>
        internal static string PurpleTeamName {
            get {
                return ResourceManager.GetString("PurpleTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantom Zone.
        /// </summary>
        internal static string PZName {
            get {
                return ResourceManager.GetString("PZName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank turns faster.  Good for dodging..
        /// </summary>
        internal static string QuickTurnDescription {
            get {
                return ResourceManager.GetString("QuickTurnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Turn.
        /// </summary>
        internal static string QuickTurnName {
            get {
                return ResourceManager.GetString("QuickTurnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Fire.
        /// </summary>
        internal static string RapidFireName {
            get {
                return ResourceManager.GetString("RapidFireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s yours, prevent other teams from taking it.  If it&apos;s not take it to your base to capture it!.
        /// </summary>
        internal static string RedTeamDescription {
            get {
                return ResourceManager.GetString("RedTeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Team.
        /// </summary>
        internal static string RedTeamName {
            get {
                return ResourceManager.GetString("RedTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riccochet.
        /// </summary>
        internal static string RiccoName {
            get {
                return ResourceManager.GetString("RiccoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Bullet.
        /// </summary>
        internal static string SBName {
            get {
                return ResourceManager.GetString("SBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string ShieldName {
            get {
                return ResourceManager.GetString("ShieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock Wave.
        /// </summary>
        internal static string ShockWaveName {
            get {
                return ResourceManager.GetString("ShockWaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth.
        /// </summary>
        internal static string StealthName {
            get {
                return ResourceManager.GetString("StealthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steamroller.
        /// </summary>
        internal static string SteamrollerName {
            get {
                return ResourceManager.GetString("SteamrollerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        internal static string TinyName {
            get {
                return ResourceManager.GetString("TinyName", resourceCulture);
            }
        }
    }
}
