//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BZFS.PlayerAdministration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BZFS.PlayerAdministration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate player: .
        /// </summary>
        internal static string ArgumentNoUserMessage {
            get {
                return ResourceManager.GetString("ArgumentNoUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banning player: .
        /// </summary>
        internal static string BanCompleteMessage {
            get {
                return ResourceManager.GetString("BanCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        internal static string BanDefaultReason {
            get {
                return ResourceManager.GetString("BanDefaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban immunity in place for player: .
        /// </summary>
        internal static string BanImmunityMessage {
            get {
                return ResourceManager.GetString("BanImmunityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uknown ban arguments useage, /ban PLAYER BanType[WEAK/STRONG] Durration[#D#M/FULL] REASON.
        /// </summary>
        internal static string BanMalformedMessage {
            get {
                return ResourceManager.GetString("BanMalformedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required permissions to use the Kick command.
        /// </summary>
        internal static string BanNonAuthMessage {
            get {
                return ResourceManager.GetString("BanNonAuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not ban yourself, that would be stupid.
        /// </summary>
        internal static string BanSelfMessage {
            get {
                return ResourceManager.GetString("BanSelfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicking player:.
        /// </summary>
        internal static string KickCompleteMessage {
            get {
                return ResourceManager.GetString("KickCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick immunity in place for player: .
        /// </summary>
        internal static string KickImmunityMessage {
            get {
                return ResourceManager.GetString("KickImmunityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required permissions to use the Kick command.
        /// </summary>
        internal static string KickNonAuthMessage {
            get {
                return ResourceManager.GetString("KickNonAuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not kick yourself, that would be silly.
        /// </summary>
        internal static string KickSelfMessage {
            get {
                return ResourceManager.GetString("KickSelfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are being kicked for: .
        /// </summary>
        internal static string KickTargetMessagePrefix {
            get {
                return ResourceManager.GetString("KickTargetMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE bans (
        ///    ID         INTEGER  PRIMARY KEY AUTOINCREMENT,
        ///    BanID      STRING,
        ///    BanAddress STRING,
        ///    BanHost    STRING,
        ///    Author     STRING,
        ///    Reason     STRING,
        ///    CreateTime DATETIME,
        ///    EndTime    DATETIME,
        ///    Active     BOOLEAN
        ///);.
        /// </summary>
        internal static string SQLiteCreateString {
            get {
                return ResourceManager.GetString("SQLiteCreateString", resourceCulture);
            }
        }
    }
}
